#!/bin/bash
ip link set dev eth0 up
ip addr add 192.168.150.130/26 dev eth0
ip link set dev eth1 up
ip addr add 128.124.240.225/27 dev eth1
ip route add default via 128.124.240.226
iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
